### ISSUE TITLE
Does not seem to work?

### ISSUE THREAD

**Issue by ProjectInfinity** [xcatliu/simplemde-theme-dark#1]
Following the instructions, replacing the CSS with yours, the following happens:

![screenshot](http://puu.sh/tbeq0/e752d02857.png)

http://puu.sh/tbeq0/e752d02857.png

Reverting to the official CSS fixes it.

**Comment by xcatliu** [comment]
Thanks for your feedback.
I know what is going wrong, the `raw.githubusercontent.com` cannot use as a cnd, please use this instead:

```
https://cdn.rawgit.com/xcatliu/simplemde-theme-dark/master/dist/simplemde-theme-dark.min.css
```

I've updated the `README.md`

Please tell me if this issue solved, thanks!
